const userTypes = {
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    SIGN_IN_SUCCES: 'SIGN_IN_SUCCES',
    SIGN_UP_SUCCES: 'SIGN_UP_SUCCES',
    SIGN_UP_ERROR: 'SIGN_UP_ERROR',
    RESET_PASSWORD_ERROR: 'RESET_PASSWORD_ERROR',
    RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS'
}

export default userTypes